-- ============================================================================
-- sutaz.ca — Lead seed (210 source rows → deduplicated to unique leads)
-- ============================================================================
-- Source: Canada_210_Real_Verified_Leads.xlsx (210 rows).
-- Data-quality fix vs the blueprint: the source contains known duplicates
-- (e.g., "Azuro Digital (Toronto Regional Account)" appears at rows 0, 30, 60
-- with identical province/city/industry/company/domain/scope). The blueprint
-- seeded all 210 then DELETE-d duplicates on production — sloppy.
--
-- This seed loads the 210 rows into a TEMP staging table, then INSERTs only
-- DISTINCT (province, city, industry, company_name, website_domain,
-- automation_scope) rows into `leads`. No DELETE on the live table.
-- ============================================================================

-- Temporary staging table — dropped automatically at session end.
CREATE TEMP TABLE _leads_stage (
  province        canadian_province,
  city            TEXT,
  industry        industry_category,
  company_name    TEXT,
  website_domain  TEXT,
  automation_scope automation_pitch
);

-- All 210 source rows, verbatim from the spreadsheet (rows 0-209).
INSERT INTO _leads_stage VALUES
-- ONTARIO (rows 0-69)
('ontario','Toronto','web_design_seo','Azuro Digital (Toronto Regional Account)','https://www.azurodigital.com','lead_data_synchronization'),
('ontario','Ottawa','commercial_construction','Build It By Design - Ottawa Operational Branch','https://www.builditbydesign.ca','site_milestone_updates'),
('ontario','Mississauga','real_estate_brokerage','RE/MAX Hallmark Realty (Mississauga Corporate Unit)','https://www.remaxhallmark.com','lead_to_booking_system'),
('ontario','Oakville','digital_marketing_agency','Search + Gather (Oakville Regional Account)','https://www.searchgather.com','client_onboarding_pipeline'),
('ontario','Markham','construction_engineering','Maple Reinders - Markham Operational Branch','https://www.maple.ca','workflow_automation'),
('ontario','Hamilton','real_estate_brokerage','RE/MAX Realtron Realty (Hamilton Corporate Unit)','https://www.remaxrealtron.com','lead_to_booking_system'),
('ontario','London','creative_agency','Pound & Grain (London Regional Account)','https://www.poundandgrain.com','creative_asset_pipeline'),
('ontario','Kitchener','commercial_contractor','Gillam Group - Kitchener Operational Branch','https://www.gillamgroup.com','workflow_automation'),
('ontario','Vaughan','real_estate_brokerage','RE/MAX Professionals (Vaughan Corporate Unit)','https://www.remaxprofessionals.ca','lead_to_booking_system'),
('ontario','Burlington','digital_marketing_agency','Candybox Marketing (Burlington Regional Account)','https://www.candyboxmarketing.com','client_onboarding_pipeline'),
('ontario','Toronto','contracting_building','Sora Construction - Toronto Operational Branch','https://www.soraconstruction.com','workflow_automation'),
('ontario','Ottawa','real_estate_brokerage','Royal LePage Signature Realty (Ottawa Corporate Unit)','https://www.royallepagesignature.com','lead_to_booking_system'),
('ontario','Mississauga','marketing_seo','Ignite Digital (Mississauga Regional Account)','https://www.ignitedigital.com','workflow_automation'),
('ontario','Oakville','general_contractor','Schilthuis Construction - Oakville Operational Branch','https://www.schilthuis.com','supplier_quote_collator'),
('ontario','Markham','real_estate_brokerage','Royal LePage Real Estate Services (Markham Corporate Unit)','https://www.royallepage.ca','lead_to_booking_system'),
('ontario','Hamilton','ecommerce_digital_agency','Northern Commerce (Hamilton Regional Account)','https://www.northern.co','ecommerce_tracking'),
('ontario','London','infrastructure_construction','EllisDon Corporation - London Operational Branch','https://www.ellisdon.com','workflow_automation'),
('ontario','Kitchener','real_estate_brokerage','Royal LePage Team Realty (Kitchener Corporate Unit)','https://www.teamrealty.ca','lead_to_booking_system'),
('ontario','Vaughan','full_service_marketing','BrandLume Inc. (Vaughan Regional Account)','https://www.brandlume.com','workflow_automation'),
('ontario','Burlington','general_contracting_engineering','Pomerleau Inc. - Burlington Operational Branch','https://www.pomerleau.ca','workflow_automation'),
('ontario','Toronto','real_estate_brokerage','Century 21 Leading Edge Realty (Toronto Corporate Unit)','https://www.leadingedgerealty.com','lead_to_booking_system'),
('ontario','Ottawa','digital_marketing_agency','Zigma Internet Marketing (Ottawa Regional Account)','https://www.zigma.ca','client_onboarding_pipeline'),
('ontario','Mississauga','commercial_construction','Bird Construction - Mississauga Operational Branch','https://www.bird.ca','workflow_automation'),
('ontario','Oakville','real_estate_brokerage','Century 21 Miller Real Estate (Oakville Corporate Unit)','https://www.c21miller.com','lead_to_booking_system'),
('ontario','Markham','digital_marketing_agency','dNOVO Group (Markham Regional Account)','https://www.dnovogroup.com','workflow_automation'),
('ontario','Hamilton','general_contractor','Ball Construction - Hamilton Operational Branch','https://www.ballcon.com','supplier_quote_collator'),
('ontario','London','real_estate_brokerage','Right At Home Realty (London Corporate Unit)','https://www.rightathomerealty.com','lead_to_booking_system'),
('ontario','Kitchener','ecommerce_digital_agency','1 At Bat Media (Kitchener Regional Account)','https://www.1atbatmedia.com','workflow_automation'),
('ontario','Vaughan','general_contractor','Buttcon Limited - Vaughan Operational Branch','https://www.buttcon.com','supplier_quote_collator'),
('ontario','Burlington','real_estate_brokerage','Chestnut Park Real Estate (Burlington Corporate Unit)','https://www.chestnutpark.com','lead_to_booking_system'),
('ontario','Toronto','web_design_seo','Azuro Digital (Toronto Regional Account)','https://www.azurodigital.com','lead_data_synchronization'),
('ontario','Ottawa','commercial_construction','Build It By Design - Ottawa Operational Branch','https://www.builditbydesign.ca','site_milestone_updates'),
('ontario','Mississauga','real_estate_brokerage','Harvey Kalles Real Estate (Mississauga Corporate Unit)','https://www.harveykalles.com','lead_to_booking_system'),
('ontario','Oakville','digital_marketing_agency','Search + Gather (Oakville Regional Account)','https://www.searchgather.com','client_onboarding_pipeline'),
('ontario','Markham','construction_engineering','Maple Reinders - Markham Operational Branch','https://www.maple.ca','workflow_automation'),
('ontario','Hamilton','real_estate_brokerage','Fox Marin Real Estate (Hamilton Corporate Unit)','https://foxmarin.ca','lead_to_booking_system'),
('ontario','London','creative_agency','Pound & Grain (London Regional Account)','https://www.poundandgrain.com','creative_asset_pipeline'),
('ontario','Kitchener','commercial_contractor','Gillam Group - Kitchener Operational Branch','https://www.gillamgroup.com','workflow_automation'),
('ontario','Vaughan','real_estate_brokerage','Sage Real Estate (Vaughan Corporate Unit)','https://www.sagerealestate.com','lead_to_booking_system'),
('ontario','Burlington','digital_marketing_agency','Candybox Marketing (Burlington Regional Account)','https://www.candyboxmarketing.com','client_onboarding_pipeline'),
('ontario','Toronto','contracting_building','Sora Construction - Toronto Operational Branch','https://www.soraconstruction.com','workflow_automation'),
('ontario','Ottawa','real_estate_brokerage','Metropolitan Commercial Realty (Ottawa Corporate Unit)','https://www.metropolitancommercial.com','lead_to_booking_system'),
('ontario','Mississauga','marketing_seo','Ignite Digital (Mississauga Regional Account)','https://www.ignitedigital.com','workflow_automation'),
('ontario','Oakville','general_contractor','Schilthuis Construction - Oakville Operational Branch','https://www.schilthuis.com','supplier_quote_collator'),
('ontario','Markham','property_management','Buttonwood Property Management (Markham Corporate Unit)','https://www.buttonwood.ca','maintenance_triage'),
('ontario','Hamilton','ecommerce_digital_agency','Northern Commerce (Hamilton Regional Account)','https://www.northern.co','ecommerce_tracking'),
('ontario','London','infrastructure_construction','EllisDon Corporation - London Operational Branch','https://www.ellisdon.com','workflow_automation'),
('ontario','Kitchener','real_estate_brokerage','RE/MAX Hallmark Realty (Kitchener Corporate Unit)','https://www.remaxhallmark.com','lead_to_booking_system'),
('ontario','Vaughan','full_service_marketing','BrandLume Inc. (Vaughan Regional Account)','https://www.brandlume.com','workflow_automation'),
('ontario','Burlington','general_contracting_engineering','Pomerleau Inc. - Burlington Operational Branch','https://www.pomerleau.ca','workflow_automation'),
('ontario','Toronto','real_estate_brokerage','RE/MAX Realtron Realty (Toronto Corporate Unit)','https://www.remaxrealtron.com','lead_to_booking_system'),
('ontario','Ottawa','digital_marketing_agency','Zigma Internet Marketing (Ottawa Regional Account)','https://www.zigma.ca','client_onboarding_pipeline'),
('ontario','Mississauga','commercial_construction','Bird Construction - Mississauga Operational Branch','https://www.bird.ca','workflow_automation'),
('ontario','Oakville','real_estate_brokerage','RE/MAX Professionals (Oakville Corporate Unit)','https://www.remaxprofessionals.ca','lead_to_booking_system'),
('ontario','Markham','digital_marketing_agency','dNOVO Group (Markham Regional Account)','https://www.dnovogroup.com','workflow_automation'),
('ontario','Hamilton','general_contractor','Ball Construction - Hamilton Operational Branch','https://www.ballcon.com','supplier_quote_collator'),
('ontario','London','real_estate_brokerage','Royal LePage Signature Realty (London Corporate Unit)','https://www.royallepagesignature.com','lead_to_booking_system'),
('ontario','Kitchener','ecommerce_digital_agency','1 At Bat Media (Kitchener Regional Account)','https://www.1atbatmedia.com','workflow_automation'),
('ontario','Vaughan','general_contractor','Buttcon Limited - Vaughan Operational Branch','https://www.buttcon.com','supplier_quote_collator'),
('ontario','Burlington','real_estate_brokerage','Royal LePage Real Estate Services (Burlington Corporate Unit)','https://www.royallepage.ca','lead_to_booking_system'),
('ontario','Toronto','web_design_seo','Azuro Digital (Toronto Regional Account)','https://www.azurodigital.com','lead_data_synchronization'),
('ontario','Ottawa','commercial_construction','Build It By Design - Ottawa Operational Branch','https://www.builditbydesign.ca','site_milestone_updates'),
('ontario','Mississauga','real_estate_brokerage','Royal LePage Team Realty (Mississauga Corporate Unit)','https://www.teamrealty.ca','lead_to_booking_system'),
('ontario','Oakville','digital_marketing_agency','Search + Gather (Oakville Regional Account)','https://www.searchgather.com','client_onboarding_pipeline'),
('ontario','Markham','construction_engineering','Maple Reinders - Markham Operational Branch','https://www.maple.ca','workflow_automation'),
('ontario','Hamilton','real_estate_brokerage','Century 21 Leading Edge Realty (Hamilton Corporate Unit)','https://www.leadingedgerealty.com','lead_to_booking_system'),
('ontario','London','creative_agency','Pound & Grain (London Regional Account)','https://www.poundandgrain.com','creative_asset_pipeline'),
('ontario','Kitchener','commercial_contractor','Gillam Group - Kitchener Operational Branch','https://www.gillamgroup.com','workflow_automation'),
('ontario','Vaughan','real_estate_brokerage','Century 21 Miller Real Estate (Vaughan Corporate Unit)','https://www.c21miller.com','lead_to_booking_system'),
('ontario','Burlington','digital_marketing_agency','Candybox Marketing (Burlington Regional Account)','https://www.candyboxmarketing.com','client_onboarding_pipeline'),
-- ALBERTA (rows 70-139)
('alberta','Calgary','digital_experience_agency','Critical Mass (Calgary Regional Account)','https://www.criticalmass.com','workflow_automation'),
('alberta','Edmonton','commercial_construction','BUILD IT Calgary - Edmonton Operational Branch','https://www.buildit.ca','workflow_automation'),
('alberta','Red Deer','real_estate_brokerage','RE/MAX Real Estate Central (Red Deer Corporate Unit)','https://www.remaxcentral.ca','lead_to_booking_system'),
('alberta','Lethbridge','digital_marketing_agency','Konstruct Digital (Lethbridge Regional Account)','https://www.konstructdigital.com','client_onboarding_pipeline'),
('alberta','Fort McMurray','general_contractor','Statera Contracting - Fort McMurray Operational Branch','https://www.stateracontracting.com','supplier_quote_collator'),
('alberta','Medicine Hat','real_estate_brokerage','RE/MAX River City (Medicine Hat Corporate Unit)','https://www.remaxrivercity.com','lead_to_booking_system'),
('alberta','Grande Prairie','digital_marketing_agency','CAYK Marketing (Grande Prairie Regional Account)','https://www.cayk.ca','client_onboarding_pipeline'),
('alberta','Airdrie','home_renovations','Talee Renovations - Airdrie Operational Branch','https://www.taleerenovations.com','client_scheduling_ai'),
('alberta','St. Albert','real_estate_brokerage','RE/MAX Real Estate Edmonton (St. Albert Corporate Unit)','https://www.remax.ca','lead_to_booking_system'),
('alberta','Sherwood Park','software_tech_agency','DevFacto (Sherwood Park Regional Account)','https://www.devfacto.com','workflow_automation'),
('alberta','Calgary','custom_home_builder','Metrik Developments - Calgary Operational Branch','https://www.metrikdevelopments.com','compliance_automation'),
('alberta','Edmonton','real_estate_brokerage','CIR Realty (Edmonton Corporate Unit)','https://www.cirrealty.ca','lead_to_booking_system'),
('alberta','Red Deer','creative_agency','Lift Interactive (Red Deer Regional Account)','https://www.liftinteractive.com','workflow_automation'),
('alberta','Lethbridge','home_remodeling','Calgary Bathworks - Lethbridge Operational Branch','https://www.calgarybathworks.com','supply_order_automation'),
('alberta','Fort McMurray','real_estate_brokerage','Royal LePage Benchmark (Fort McMurray Corporate Unit)','https://www.royallepagebenchmark.ca','lead_to_booking_system'),
('alberta','Medicine Hat','digital_marketing_agency','Top Draw (Medicine Hat Regional Account)','https://www.topdraw.com','workflow_automation'),
('alberta','Grande Prairie','general_contractor','Westcor Construction - Grande Prairie Operational Branch','https://www.westcor.net','workflow_automation'),
('alberta','Airdrie','real_estate_brokerage','Royal LePage Noralta Real Estate (Airdrie Corporate Unit)','https://www.noralta.com','lead_to_booking_system'),
('alberta','St. Albert','digital_marketing_agency','Vovia (St. Albert Regional Account)','https://www.vovia.com','workflow_automation'),
('alberta','Sherwood Park','commercial_construction','Carlson Construction - Sherwood Park Operational Branch','https://www.avcarlson.ca','workflow_automation'),
('alberta','Calgary','real_estate_brokerage','Century 21 Bamber Real Estate (Calgary Corporate Unit)','https://www.bamberrealty.com','lead_to_booking_system'),
('alberta','Edmonton','full_service_marketing','ZGM Modern Marketing (Edmonton Regional Account)','https://www.zgm.ca','workflow_automation'),
('alberta','Red Deer','general_contracting_engineering','Chandos Construction - Red Deer Operational Branch','https://www.chandos.com','workflow_automation'),
('alberta','Lethbridge','real_estate_brokerage','Century 21 Foothills Real Estate (Lethbridge Corporate Unit)','https://www.c21foothills.com','lead_to_booking_system'),
('alberta','Fort McMurray','b2b_digital_marketing','Redstone Marketing (Fort McMurray Regional Account)','https://www.redstonemarketing.ca','workflow_automation'),
('alberta','Medicine Hat','custom_home_builder','Alair Homes Calgary - Medicine Hat Operational Branch','https://www.alairhomes.ca','compliance_automation'),
('alberta','Grande Prairie','real_estate_brokerage','Maxwell Capital Realty (Grande Prairie Corporate Unit)','https://www.maxwellrealty.ca','lead_to_booking_system'),
('alberta','Airdrie','creative_agency','Fluency Digital (Airdrie Regional Account)','https://www.fluencydigital.com','workflow_automation'),
('alberta','St. Albert','residential_construction','Hopewell Residential - St. Albert Operational Branch','https://www.hopewellresidential.com','workflow_automation'),
('alberta','Sherwood Park','real_estate_brokerage','Maxwell Canyon Creek (Sherwood Park Corporate Unit)','https://www.maxwellrealty.ca','lead_to_booking_system'),
('alberta','Calgary','digital_experience_agency','Critical Mass (Calgary Regional Account)','https://www.criticalmass.com','workflow_automation'),
('alberta','Edmonton','industrial_construction','ClearStream Energy Services - Edmonton Operational Branch','https://www.clearstreamenergy.ca','fleet_log_aggregator'),
('alberta','Red Deer','real_estate_brokerage','eXp Realty Alberta (Red Deer Corporate Unit)','https://www.exprealty.ca','lead_to_booking_system'),
('alberta','Lethbridge','digital_marketing_agency','Konstruct Digital (Lethbridge Regional Account)','https://www.konstructdigital.com','client_onboarding_pipeline'),
('alberta','Fort McMurray','residential_construction','Jayman Built - Fort McMurray Operational Branch','https://www.jayman.com','workflow_automation'),
('alberta','Medicine Hat','real_estate_brokerage','Sutton Group Canwest (Medicine Hat Corporate Unit)','https://www.suttongroup.com','lead_to_booking_system'),
('alberta','Grande Prairie','digital_marketing_agency','CAYK Marketing (Grande Prairie Regional Account)','https://www.cayk.ca','client_onboarding_pipeline'),
('alberta','Airdrie','residential_construction','Morrison Homes - Airdrie Operational Branch','https://www.morrisonhomes.ca','workflow_automation'),
('alberta','St. Albert','real_estate_brokerage','Coldwell Banker Mountain Central (St. Albert Corporate Unit)','https://www.coldwellbanker.ca','lead_to_booking_system'),
('alberta','Sherwood Park','software_tech_agency','DevFacto (Sherwood Park Regional Account)','https://www.devfacto.com','workflow_automation'),
('alberta','Calgary','residential_construction','Shane Homes - Calgary Operational Branch','https://www.shanehomes.com','workflow_automation'),
('alberta','Edmonton','real_estate_brokerage','Emerald Management & Realty (Edmonton Corporate Unit)','https://www.emeraldmanagement.com','lead_to_booking_system'),
('alberta','Red Deer','creative_agency','Lift Interactive (Red Deer Regional Account)','https://www.liftinteractive.com','workflow_automation'),
('alberta','Lethbridge','residential_construction','Cedarglen Homes - Lethbridge Operational Branch','https://www.cedarglenhomes.com','workflow_automation'),
('alberta','Fort McMurray','real_estate_brokerage','Bode Canada Realty (Fort McMurray Corporate Unit)','https://www.bode.ca','lead_to_booking_system'),
('alberta','Medicine Hat','digital_marketing_agency','Top Draw (Medicine Hat Regional Account)','https://www.topdraw.com','workflow_automation'),
('alberta','Grande Prairie','commercial_construction','BUILD IT Calgary - Grande Prairie Operational Branch','https://www.buildit.ca','workflow_automation'),
('alberta','Airdrie','real_estate_brokerage','RE/MAX Real Estate Central (Airdrie Corporate Unit)','https://www.remaxcentral.ca','lead_to_booking_system'),
('alberta','St. Albert','digital_marketing_agency','Vovia (St. Albert Regional Account)','https://www.vovia.com','workflow_automation'),
('alberta','Sherwood Park','general_contractor','Statera Contracting - Sherwood Park Operational Branch','https://www.stateracontracting.com','supplier_quote_collator'),
('alberta','Calgary','real_estate_brokerage','RE/MAX River City (Calgary Corporate Unit)','https://www.remaxrivercity.com','lead_to_booking_system'),
('alberta','Edmonton','full_service_marketing','ZGM Modern Marketing (Edmonton Regional Account)','https://www.zgm.ca','workflow_automation'),
('alberta','Red Deer','home_renovations','Talee Renovations - Red Deer Operational Branch','https://www.taleerenovations.com','client_scheduling_ai'),
('alberta','Lethbridge','real_estate_brokerage','RE/MAX Real Estate Edmonton (Lethbridge Corporate Unit)','https://www.remax.ca','lead_to_booking_system'),
('alberta','Fort McMurray','b2b_digital_marketing','Redstone Marketing (Fort McMurray Regional Account)','https://www.redstonemarketing.ca','workflow_automation'),
('alberta','Medicine Hat','custom_home_builder','Metrik Developments - Medicine Hat Operational Branch','https://www.metrikdevelopments.com','compliance_automation'),
('alberta','Grande Prairie','real_estate_brokerage','CIR Realty (Grande Prairie Corporate Unit)','https://www.cirrealty.ca','lead_to_booking_system'),
('alberta','Airdrie','creative_agency','Fluency Digital (Airdrie Regional Account)','https://www.fluencydigital.com','workflow_automation'),
('alberta','St. Albert','home_remodeling','Calgary Bathworks - St. Albert Operational Branch','https://www.calgarybathworks.com','supply_order_automation'),
('alberta','Sherwood Park','real_estate_brokerage','Royal LePage Benchmark (Sherwood Park Corporate Unit)','https://www.royallepagebenchmark.ca','lead_to_booking_system'),
('alberta','Calgary','digital_experience_agency','Critical Mass (Calgary Regional Account)','https://www.criticalmass.com','workflow_automation'),
('alberta','Edmonton','general_contractor','Westcor Construction - Edmonton Operational Branch','https://www.westcor.net','workflow_automation'),
('alberta','Red Deer','real_estate_brokerage','Royal LePage Noralta Real Estate (Red Deer Corporate Unit)','https://www.noralta.com','lead_to_booking_system'),
('alberta','Lethbridge','digital_marketing_agency','Konstruct Digital (Lethbridge Regional Account)','https://www.konstructdigital.com','client_onboarding_pipeline'),
('alberta','Fort McMurray','commercial_construction','Carlson Construction - Fort McMurray Operational Branch','https://www.avcarlson.ca','workflow_automation'),
('alberta','Medicine Hat','real_estate_brokerage','Century 21 Bamber Real Estate (Medicine Hat Corporate Unit)','https://www.bamberrealty.com','lead_to_booking_system'),
('alberta','Grande Prairie','digital_marketing_agency','CAYK Marketing (Grande Prairie Regional Account)','https://www.cayk.ca','client_onboarding_pipeline'),
('alberta','Airdrie','general_contracting_engineering','Chandos Construction - Airdrie Operational Branch','https://www.chandos.com','workflow_automation'),
('alberta','St. Albert','real_estate_brokerage','Century 21 Foothills Real Estate (St. Albert Corporate Unit)','https://www.c21foothills.com','lead_to_booking_system'),
('alberta','Sherwood Park','software_tech_agency','DevFacto (Sherwood Park Regional Account)','https://www.devfacto.com','workflow_automation'),
-- BRITISH COLUMBIA (rows 140-209)
('british_columbia','Vancouver','digital_marketing_agency','Major Tom (Vancouver Regional Account)','https://www.majortom.com','workflow_automation'),
('british_columbia','Victoria','infrastructure_construction','Ledcor Group - Victoria Operational Branch','https://www.ledcor.com','workflow_automation'),
('british_columbia','Kelowna','real_estate_brokerage','Oakwyn Realty (Kelowna Corporate Unit)','https://www.oakwyn.com','lead_to_booking_system'),
('british_columbia','Burnaby','performance_marketing','Thrive Digital (Burnaby Regional Account)','https://www.thrivedigital.com','reporting_automation'),
('british_columbia','Surrey','commercial_construction','Graham Construction - Surrey Operational Branch','https://www.graham.ca','workflow_automation'),
('british_columbia','Richmond','real_estate_brokerage','Stilhavn Real Estate Services (Richmond Corporate Unit)','https://www.stilhavn.com','lead_to_booking_system'),
('british_columbia','Coquitlam','digital_marketing_agency','Jelly Digital Marketing & PR (Coquitlam Regional Account)','https://jellymarketing.ca','workflow_automation'),
('british_columbia','Nanaimo','commercial_construction','Ventana Construction - Nanaimo Operational Branch','https://www.ventanaconstruction.com','workflow_automation'),
('british_columbia','Kamloops','real_estate_brokerage','Sutton Group West Coast Realty (Kamloops Corporate Unit)','https://www.suttongroup.com','lead_to_booking_system'),
('british_columbia','North Vancouver','ecommerce_web_design','Pixel Union (North Vancouver Regional Account)','https://www.pixelunion.net','workflow_automation'),
('british_columbia','Vancouver','general_contracting_engineering','Axiom Builders - Vancouver Operational Branch','https://www.axiombuilders.ca','workflow_automation'),
('british_columbia','Victoria','real_estate_brokerage','Stonehaus Realty (Victoria Corporate Unit)','https://www.stonehausrealty.ca','lead_to_booking_system'),
('british_columbia','Kelowna','digital_product_studio','Engine Digital (Kelowna Regional Account)','https://www.enginedigital.com','workflow_automation'),
('british_columbia','Burnaby','general_contractor','Wales McLelland Construction - Burnaby Operational Branch','https://www.walesmclelland.com','workflow_automation'),
('british_columbia','Surrey','real_estate_brokerage','TRG Realty (Surrey Corporate Unit)','https://www.trgrealty.ca','lead_to_booking_system'),
('british_columbia','Richmond','creative_agency','Skyrocket Digital (Richmond Regional Account)','https://www.skyrocket.me','workflow_automation'),
('british_columbia','Coquitlam','renewable_energy','Borea Construction BC - Coquitlam Operational Branch','https://www.boreaconstruction.com','workflow_automation'),
('british_columbia','Nanaimo','real_estate_brokerage','Macdonald Realty (Nanaimo Corporate Unit)','https://www.macrealty.com','lead_to_booking_system'),
('british_columbia','Kamloops','digital_marketing_agency','AntiSocial Solutions (Kamloops Regional Account)','https://www.antisocialsolutions.com','workflow_automation'),
('british_columbia','North Vancouver','custom_home_builder','Alair Homes Vancouver - North Vancouver Operational Branch','https://www.alairhomes.ca','workflow_automation'),
('british_columbia','Vancouver','real_estate_brokerage','Dexter Realty (Vancouver Corporate Unit)','https://www.dexterrealty.com','lead_to_booking_system'),
('british_columbia','Victoria','b2b_tech_marketing','Stryve Digital (Victoria Regional Account)','https://www.stryve.digital','workflow_automation'),
('british_columbia','Kelowna','commercial_construction','Townline Construction - Kelowna Operational Branch','https://www.townline.com','workflow_automation'),
('british_columbia','Burnaby','real_estate_brokerage','RE/MAX Camosun (Burnaby Corporate Unit)','https://www.remaxcamosun.com','lead_to_booking_system'),
('british_columbia','Surrey','branding_web_design','Massive Media (Surrey Regional Account)','https://www.massivemedia.ca','workflow_automation'),
('british_columbia','Richmond','real_estate_brokerage','Concert Properties - Richmond Operational Branch','https://www.concertproperties.com','workflow_automation'),
('british_columbia','Coquitlam','real_estate_brokerage','RE/MAX Crest Realty (Coquitlam Corporate Unit)','https://www.remax.ca','lead_to_booking_system'),
('british_columbia','Nanaimo','digital_strategy','Magnify Digital (Nanaimo Regional Account)','https://www.magnifydigital.com','workflow_automation'),
('british_columbia','Kamloops','general_contracting_engineering','Bosa Construction - Kamloops Operational Branch','https://www.bosa.com','workflow_automation'),
('british_columbia','North Vancouver','real_estate_brokerage','Century 21 Assurance Realty (North Vancouver Corporate Unit)','https://www.c21kelowna.com','lead_to_booking_system'),
('british_columbia','Vancouver','digital_marketing_agency','Major Tom (Vancouver Regional Account)','https://www.majortom.com','workflow_automation'),
('british_columbia','Victoria','infrastructure_construction','Ledcor Group - Victoria Operational Branch','https://www.ledcor.com','workflow_automation'),
('british_columbia','Kelowna','real_estate_brokerage','Royal LePage Sussex (Kelowna Corporate Unit)','https://www.royallepage.ca','lead_to_booking_system'),
('british_columbia','Burnaby','performance_marketing','Thrive Digital (Burnaby Regional Account)','https://www.thrivedigital.com','reporting_automation'),
('british_columbia','Surrey','commercial_construction','Graham Construction - Surrey Operational Branch','https://www.graham.ca','workflow_automation'),
('british_columbia','Richmond','real_estate_brokerage','Royal LePage Wolstencroft (Richmond Corporate Unit)','https://www.royallepage.ca','lead_to_booking_system'),
('british_columbia','Coquitlam','digital_marketing_agency','Jelly Digital Marketing & PR (Coquitlam Regional Account)','https://jellymarketing.ca','workflow_automation'),
('british_columbia','Nanaimo','commercial_construction','Ventana Construction - Nanaimo Operational Branch','https://www.ventanaconstruction.com','workflow_automation'),
('british_columbia','Kamloops','real_estate_brokerage','Nu Stream Realty (Kamloops Corporate Unit)','https://www.nustreamrealty.com','lead_to_booking_system'),
('british_columbia','North Vancouver','ecommerce_web_design','Pixel Union (North Vancouver Regional Account)','https://www.pixelunion.net','workflow_automation'),
('british_columbia','Vancouver','general_contracting_engineering','Axiom Builders - Vancouver Operational Branch','https://www.axiombuilders.ca','workflow_automation'),
('british_columbia','Victoria','real_estate_brokerage','Sotheby''s International Realty Canada (Victoria Corporate Unit)','https://www.sothebysrealty.ca','lead_to_booking_system'),
('british_columbia','Kelowna','digital_product_studio','Engine Digital (Kelowna Regional Account)','https://www.enginedigital.com','workflow_automation'),
('british_columbia','Burnaby','general_contractor','Wales McLelland Construction - Burnaby Operational Branch','https://www.walesmclelland.com','workflow_automation'),
('british_columbia','Surrey','real_estate_brokerage','Engel & Völkers Vancouver (Surrey Corporate Unit)','https://www.vancouver.evrealestate.com','lead_to_booking_system'),
('british_columbia','Richmond','creative_agency','Skyrocket Digital (Richmond Regional Account)','https://www.skyrocket.me','workflow_automation'),
('british_columbia','Coquitlam','renewable_energy','Borea Construction BC - Coquitlam Operational Branch','https://www.boreaconstruction.com','workflow_automation'),
('british_columbia','Nanaimo','real_estate_brokerage','Oakwyn Realty (Nanaimo Corporate Unit)','https://www.oakwyn.com','lead_to_booking_system'),
('british_columbia','Kamloops','digital_marketing_agency','AntiSocial Solutions (Kamloops Regional Account)','https://www.antisocialsolutions.com','workflow_automation'),
('british_columbia','North Vancouver','custom_home_builder','Alair Homes Vancouver - North Vancouver Operational Branch','https://www.alairhomes.ca','workflow_automation'),
('british_columbia','Vancouver','real_estate_brokerage','Stilhavn Real Estate Services (Vancouver Corporate Unit)','https://www.stilhavn.com','lead_to_booking_system'),
('british_columbia','Victoria','b2b_tech_marketing','Stryve Digital (Victoria Regional Account)','https://www.stryve.digital','workflow_automation'),
('british_columbia','Kelowna','commercial_construction','Townline Construction - Kelowna Operational Branch','https://www.townline.com','workflow_automation'),
('british_columbia','Burnaby','real_estate_brokerage','Sutton Group West Coast Realty (Burnaby Corporate Unit)','https://www.suttongroup.com','lead_to_booking_system'),
('british_columbia','Surrey','branding_web_design','Massive Media (Surrey Regional Account)','https://www.massivemedia.ca','workflow_automation'),
('british_columbia','Richmond','general_contracting_engineering','Concert Properties - Richmond Operational Branch','https://www.concertproperties.com','workflow_automation'),
('british_columbia','Coquitlam','real_estate_brokerage','Stonehaus Realty (Coquitlam Corporate Unit)','https://www.stonehausrealty.ca','lead_to_booking_system'),
('british_columbia','Nanaimo','digital_strategy','Magnify Digital (Nanaimo Regional Account)','https://www.magnifydigital.com','workflow_automation'),
('british_columbia','Kamloops','general_contracting_engineering','Bosa Construction - Kamloops Operational Branch','https://www.bosa.com','workflow_automation'),
('british_columbia','North Vancouver','real_estate_brokerage','TRG Realty (North Vancouver Corporate Unit)','https://www.trgrealty.ca','lead_to_booking_system'),
('british_columbia','Vancouver','digital_marketing_agency','Major Tom (Vancouver Regional Account)','https://www.majortom.com','workflow_automation'),
('british_columbia','Victoria','infrastructure_construction','Ledcor Group - Victoria Operational Branch','https://www.ledcor.com','workflow_automation'),
('british_columbia','Kelowna','real_estate_brokerage','Macdonald Realty (Kelowna Corporate Unit)','https://www.macrealty.com','lead_to_booking_system'),
('british_columbia','Burnaby','performance_marketing','Thrive Digital (Burnaby Regional Account)','https://www.thrivedigital.com','reporting_automation'),
('british_columbia','Surrey','commercial_construction','Graham Construction - Surrey Operational Branch','https://www.graham.ca','workflow_automation'),
('british_columbia','Richmond','real_estate_brokerage','Dexter Realty (Richmond Corporate Unit)','https://www.dexterrealty.com','lead_to_booking_system'),
('british_columbia','Coquitlam','digital_marketing_agency','Jelly Digital Marketing & PR (Coquitlam Regional Account)','https://jellymarketing.ca','workflow_automation'),
('british_columbia','Nanaimo','commercial_construction','Ventana Construction - Nanaimo Operational Branch','https://www.ventanaconstruction.com','workflow_automation'),
('british_columbia','Kamloops','real_estate_brokerage','RE/MAX Camosun (Kamloops Corporate Unit)','https://www.remaxcamosun.com','lead_to_booking_system'),
('british_columbia','North Vancouver','ecommerce_web_design','Pixel Union (North Vancouver Regional Account)','https://www.pixelunion.net','workflow_automation');

-- ============================================================================
-- Deduplicated insert: only unique rows reach the production leads table.
-- ============================================================================
INSERT INTO leads (province, city, industry, company_name, website_domain, automation_scope, source)
SELECT DISTINCT ON (province, city, industry, company_name, website_domain, automation_scope)
       province, city, industry, company_name, website_domain, automation_scope, 'seed'
FROM _leads_stage
ORDER BY province, city, industry, company_name, website_domain, automation_scope;

-- Reporting (informational — surfaces how many duplicates were removed)
DO $$
DECLARE
  staged INT;
  loaded INT;
BEGIN
  SELECT count(*) INTO staged FROM _leads_stage;
  SELECT count(*) INTO loaded FROM leads WHERE source = 'seed';
  RAISE NOTICE 'Seed: % source rows staged, % unique leads loaded (% duplicates removed).',
    staged, loaded, staged - loaded;
END $$;
